metadata:
  description: BicapaCryoET simulacion2 -> PolNet pipeline
  author: BicapaCryoET v15

folders:
  root: ./
  input: ./polnet_entrada/
  output: ./polnet_salida/simulacion0002/

global:
  ntomos: 1
  seed: 2

sample:
  voi_shape: [400, 400, 200]
  voxel_size: 10
  membranes:
    - mb_type: file
      mb_file: /home/alumno25/TFM_Backup/CryoET/mrc/bicapa_simulacion0002.mrc
      mb_thick: 4.97222

tem:
  snr: 0.1
  tilt_range: [-60, 60, 3]

# Instrucciones:
#   1. Instala PolNet: pip install polnet
#   2. Ejecuta: polnet --config config_simulacion0002.yaml
#   3. El tomograma simulado estara en polnet_salida/simulacion0002/
#
# Referencia:
#   Martinez-Sanchez et al. IEEE Trans. Med. Imaging 2024
#   https://doi.org/10.1109/TMI.2024.3398401
